# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_p.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Program(object):
    def setupUi(self, Program):
        Program.setObjectName("Program")
        Program.resize(730, 388)
        self.btn_close = QtWidgets.QPushButton(Program)
        self.btn_close.setGeometry(QtCore.QRect(30, 30, 111, 41))
        self.btn_close.setObjectName("btn_close")
        self.combo_dst = QtWidgets.QComboBox(Program)
        self.combo_dst.setGeometry(QtCore.QRect(30, 110, 71, 41))
        self.combo_dst.setObjectName("combo_dst")
        self.combo_dst.addItem("")
        self.combo_dst.addItem("")
        self.combo_dst.addItem("")
        self.combo_dst.addItem("")
        self.combo_dst.addItem("")
        self.combo_dst.addItem("")
        self.combo_dst.addItem("")
        self.combo_dst.addItem("")
        self.combo_act = QtWidgets.QComboBox(Program)
        self.combo_act.setGeometry(QtCore.QRect(110, 110, 71, 41))
        self.combo_act.setObjectName("combo_act")
        self.combo_act.addItem("")
        self.combo_act.addItem("")
        self.combo_act.addItem("")
        self.combo_act.addItem("")
        self.combo_act.addItem("")
        self.combo_act.addItem("")
        self.combo_act.addItem("")
        self.combo_act.addItem("")
        self.combo_act.addItem("")
        self.combo_act.addItem("")
        self.combo_src = QtWidgets.QComboBox(Program)
        self.combo_src.setGeometry(QtCore.QRect(190, 110, 81, 41))
        self.combo_src.setObjectName("combo_src")
        self.combo_src.addItem("")
        self.combo_src.addItem("")
        self.combo_src.addItem("")
        self.combo_src.addItem("")
        self.combo_src.addItem("")
        self.combo_src.addItem("")
        self.combo_src.addItem("")
        self.combo_src.addItem("")
        self.combo_src.addItem("")
        self.combo_src.addItem("")
        self.combo_src.addItem("")
        self.combo_src.addItem("")
        self.combo_src.addItem("")
        self.btn_load = QtWidgets.QPushButton(Program)
        self.btn_load.setGeometry(QtCore.QRect(160, 30, 111, 41))
        self.btn_load.setObjectName("btn_load")
        self.edit_src = QtWidgets.QLineEdit(Program)
        self.edit_src.setGeometry(QtCore.QRect(190, 160, 81, 31))
        self.edit_src.setObjectName("edit_src")
        self.btn_add_line = QtWidgets.QPushButton(Program)
        self.btn_add_line.setGeometry(QtCore.QRect(30, 210, 71, 41))
        self.btn_add_line.setObjectName("btn_add_line")
        self.btn_remove_line = QtWidgets.QPushButton(Program)
        self.btn_remove_line.setGeometry(QtCore.QRect(110, 210, 71, 41))
        self.btn_remove_line.setObjectName("btn_remove_line")
        self.line = QtWidgets.QFrame(Program)
        self.line.setGeometry(QtCore.QRect(20, 80, 261, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Program)
        self.line_2.setGeometry(QtCore.QRect(20, 260, 261, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.btn_save_file = QtWidgets.QPushButton(Program)
        self.btn_save_file.setGeometry(QtCore.QRect(30, 290, 111, 41))
        self.btn_save_file.setObjectName("btn_save_file")
        self.btn_load_file = QtWidgets.QPushButton(Program)
        self.btn_load_file.setGeometry(QtCore.QRect(160, 290, 111, 41))
        self.btn_load_file.setObjectName("btn_load_file")
        self.groupBox = QtWidgets.QGroupBox(Program)
        self.groupBox.setGeometry(QtCore.QRect(300, 20, 181, 351))
        self.groupBox.setObjectName("groupBox")
        self.text_program = QtWidgets.QTextBrowser(self.groupBox)
        self.text_program.setGeometry(QtCore.QRect(10, 20, 161, 321))
        self.text_program.setObjectName("text_program")
        self.btn_remove_program = QtWidgets.QPushButton(Program)
        self.btn_remove_program.setGeometry(QtCore.QRect(190, 210, 81, 41))
        self.btn_remove_program.setObjectName("btn_remove_program")
        self.groupBox_2 = QtWidgets.QGroupBox(Program)
        self.groupBox_2.setGeometry(QtCore.QRect(490, 30, 231, 351))
        self.groupBox_2.setObjectName("groupBox_2")
        self.text_description = QtWidgets.QTextEdit(self.groupBox_2)
        self.text_description.setGeometry(QtCore.QRect(10, 20, 211, 321))
        self.text_description.setObjectName("text_description")

        self.retranslateUi(Program)
        QtCore.QMetaObject.connectSlotsByName(Program)

    def retranslateUi(self, Program):
        _translate = QtCore.QCoreApplication.translate
        Program.setWindowTitle(_translate("Program", "Program"))
        self.btn_close.setText(_translate("Program", "Zamknij okno"))
        self.combo_dst.setItemText(0, _translate("Program", "AH"))
        self.combo_dst.setItemText(1, _translate("Program", "AL"))
        self.combo_dst.setItemText(2, _translate("Program", "BH"))
        self.combo_dst.setItemText(3, _translate("Program", "BL"))
        self.combo_dst.setItemText(4, _translate("Program", "CH"))
        self.combo_dst.setItemText(5, _translate("Program", "CL"))
        self.combo_dst.setItemText(6, _translate("Program", "DH"))
        self.combo_dst.setItemText(7, _translate("Program", "DL"))
        self.combo_act.setItemText(0, _translate("Program", "MOV"))
        self.combo_act.setItemText(1, _translate("Program", "ADD"))
        self.combo_act.setItemText(2, _translate("Program", "SUB"))
        self.combo_act.setItemText(3, _translate("Program", "PUSH"))
        self.combo_act.setItemText(4, _translate("Program", "POP"))
        self.combo_act.setItemText(5, _translate("Program", "INT 10"))
        self.combo_act.setItemText(6, _translate("Program", "INT 15"))
        self.combo_act.setItemText(7, _translate("Program", "INT 16"))
        self.combo_act.setItemText(8, _translate("Program", "INT 21"))
        self.combo_act.setItemText(9, _translate("Program", "INT 1A"))
        self.combo_src.setItemText(0, _translate("Program", "AH"))
        self.combo_src.setItemText(1, _translate("Program", "AL"))
        self.combo_src.setItemText(2, _translate("Program", "BH"))
        self.combo_src.setItemText(3, _translate("Program", "BL"))
        self.combo_src.setItemText(4, _translate("Program", "CH"))
        self.combo_src.setItemText(5, _translate("Program", "CL"))
        self.combo_src.setItemText(6, _translate("Program", "DH"))
        self.combo_src.setItemText(7, _translate("Program", "DL"))
        self.combo_src.setItemText(8, _translate("Program", "AX"))
        self.combo_src.setItemText(9, _translate("Program", "BX"))
        self.combo_src.setItemText(10, _translate("Program", "CX"))
        self.combo_src.setItemText(11, _translate("Program", "DX"))
        self.combo_src.setItemText(12, _translate("Program", "Wart. nat."))
        self.btn_load.setText(_translate("Program", "Wczytaj program"))
        self.edit_src.setText(_translate("Program", "0"))
        self.edit_src.setPlaceholderText(_translate("Program", "0"))
        self.btn_add_line.setText(_translate("Program", "Dodaj rozkaz"))
        self.btn_remove_line.setText(_translate("Program", "Usuń rozkaz"))
        self.btn_save_file.setText(_translate("Program", "Zapisz do pliku"))
        self.btn_load_file.setText(_translate("Program", "Wczytaj z pliku"))
        self.groupBox.setTitle(_translate("Program", "Program"))
        self.btn_remove_program.setText(_translate("Program", "Usuń program"))
        self.groupBox_2.setTitle(_translate("Program", "Opis programu"))
